# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Doufu
tagline:             'A casual developer - enjoy AI and Game Development'
description:         'I enjoy learning AI, particularly interested in Deep Learning in Computer Vision'
url:                 http://lanyon.getpoole.com
baseurl:             '/personal-blog'
paginate:            5

# About/contact
author:
  name:              Jasper Lai Woen Yon
  url:               www.linkedin.com/in/woenyon
  email:             wushulai@live.com
  gravatar_md5:      4917fd2085b73c85671626b4385cbbec

# Custom vars
version:             1.0.0
